### ISSUE TITLE
Make the maximum clock speed on the CPU 16 MHz instead of 13.33 MHz

### ISSUE THREAD

**Issue by Egg-Of-Glory999** [skiselev/xi_8088#1]
There are some NEC V20's that do reach up to 16 MHz, above the 13.33 MHz on this. There could hopefully be some extra performance gains on CPUs that do get up to 16 MHz that just feels like is being left on the table.

**Comment by skiselev** [comment]
I am well aware of the existence of NEC V20HL 16 MHz CPUs. And 13.33 MHz is achieved particularly using that CPUs.

Unfortunately, in order to actually run on 16 MHz, the design will require several modifications. At least the following:
1. V20 and V20HL seem to require 50% duty cycle clock, while Intel 8088 CPUs use 33% duty cycle clock (the duty cycle is the percentage of time the clock stays high vs. the overall clock period). Xi 8088 uses Intel 8284 clock generator that provides Intel 8088 compatible clock. On lower frequencies V20 seem to function just fine with 33% clock duty cycle. But it doesn't work as well on higher frequencies, and that exactly the reason that V20HL/16 MHz will run at 13.33 MHz but not at 16 MHz.
2. In this design, all the memory transactions, including on the ISA bus, run at the CPU speed. Generally speaking, ISA devices, and video cards particularly, are designed to run at either 4.77 MHz (older, PC/XT) or at around 8 MHz (newer, AT clock). Some newer controllers, e.g. Trident TVGA8900/9000 will work up to 12 MHz. But that is already pushing the limit. It is possible to solve this by introducing wait cycles for memory access, but that's yet another change.

Here is an 11 years old thread with the discussion: https://forum.vcfed.org/index.php?threads/nec-v-20-compatibility.34782/post-426513

**Comment by Egg-Of-Glory999** [comment]
yeah, that's fair.

**Comment by tpimh** [comment]
NEC uPD71011 outputs 50% duty cycle clock, and it divides the input by 2, not by 3. However, I could only find mentions of parts that output maximum 8 or 10 MHz, not 16.
